### PR TITLE
Allow specifying list of options

### PR DESCRIPTION
**Pull request by pavlosgi**

### CODE REVIEW

**Comment by backuitist** [comment]
Hi thanks for the PR! I'm not sure to understand what you're trying to do. Could you add a test?

**Comment by pavlosgi** [comment]
Currently for lists it's only args where it is required to have at least one element. I would like an optional list, eg. --bar=1 --bar=2 --bar=3 

If you run CatDemo you can see how it looks

**Comment by backuitist** [comment]
Ok makes sense, that'd be great with a test though :)

**Comment by pavlosgi** [comment]
I agree. I'll add it in if I get a bit of extra time.

**Comment by backuitist** [comment]
Cool, you'll see it's faster to write a test than check with the demo apps, it probably is a one-liner.

**Comment by pavlosgi** [comment]
Not happy with this solution so I'll close this

**Pull request closed without merging**
